import path from 'node:path'
import { REGISTERED_PARSER_SET } from './parser-keys.ts'
import { projectRoot, readText } from './fs-utils.ts'

export interface BookRegistryEntry {
  id: string
  title: string
  shortName: string
  fullTitle: string
  corpus:
    | 'jingfang'
    | 'chenfu'
    | 'bencao'
    | 'wenbing'
    | 'jinyuan'
    | 'mingqing'
    | 'yian'
    | 'modern'
    | 'fangshu'
  school: string
  author: string
  era: string
  sourceUrl: string
  parser: string
  order: number
  color: string
  hasClauses: boolean
  doseSystem: 'han' | 'qing'
}

const CORPUS_VALUES = new Set([
  'jingfang',
  'chenfu',
  'bencao',
  'wenbing',
  'jinyuan',
  'mingqing',
  'yian',
  'modern',
  'fangshu',
])
const DOSE_VALUES = new Set(['han', 'qing'])

export function booksRegistryPath(root = projectRoot()): string {
  return path.join(root, 'data', 'ontology', 'books.json')
}

export function validateBookRegistry(entries: BookRegistryEntry[]): string[] {
  const errors: string[] = []
  const ids = new Set<string>()
  for (const entry of entries) {
    if (!entry.id) errors.push('book missing id')
    if (ids.has(entry.id)) errors.push(`duplicate book id: ${entry.id}`)
    ids.add(entry.id)
    if (!CORPUS_VALUES.has(entry.corpus)) {
      errors.push(`${entry.id}: invalid corpus ${entry.corpus}`)
    }
    if (!DOSE_VALUES.has(entry.doseSystem)) {
      errors.push(`${entry.id}: invalid doseSystem ${entry.doseSystem}`)
    }
    if (!REGISTERED_PARSER_SET.has(entry.parser)) {
      errors.push(`${entry.id}: unknown parser ${entry.parser}`)
    }
    if (!entry.title) errors.push(`${entry.id}: missing title`)
    if (typeof entry.order !== 'number') errors.push(`${entry.id}: missing order`)
  }
  return errors
}

export async function loadBookRegistry(root = projectRoot()): Promise<BookRegistryEntry[]> {
  const raw = JSON.parse(await readText(booksRegistryPath(root))) as BookRegistryEntry[]
  const errors = validateBookRegistry(raw)
  if (errors.length > 0) {
    throw new Error(`books.json invalid:\n${errors.join('\n')}`)
  }
  return [...raw].sort((a, b) => a.order - b.order)
}

export function renderBookTypesModule(entries: BookRegistryEntry[]): string {
  const ids = entries.map((entry) => entry.id)
  const idUnion = ids.map((id) => `  | '${id}'`).join('\n')
  const booksLiteral = JSON.stringify(entries, null, 2)
  return `/* eslint-disable */
/** Generated by scripts/gen-book-types.ts — do not edit by hand. */

export type BookId =
${idUnion}

export type BookCorpus =
  | 'jingfang'
  | 'chenfu'
  | 'bencao'
  | 'wenbing'
  | 'jinyuan'
  | 'mingqing'
  | 'yian'
  | 'modern'
  | 'fangshu'
export type BookDoseSystem = 'han' | 'qing'

export interface BookMeta {
  id: BookId
  title: string
  shortName: string
  fullTitle: string
  corpus: BookCorpus
  school: string
  author: string
  era: string
  sourceUrl: string
  parser: string
  order: number
  color: string
  hasClauses: boolean
  doseSystem: BookDoseSystem
}

export const BOOKS: BookMeta[] = ${booksLiteral} as BookMeta[]

export const BOOK_BY_ID: Record<BookId, BookMeta> = Object.fromEntries(
  BOOKS.map((book) => [book.id, book]),
) as Record<BookId, BookMeta>

export const BOOK_CORPUS: Record<BookId, BookCorpus> = Object.fromEntries(
  BOOKS.map((book) => [book.id, book.corpus]),
) as Record<BookId, BookCorpus>

export const JINGFANG_BOOKS: BookId[] = BOOKS.filter((book) => book.corpus === 'jingfang').map(
  (book) => book.id,
)

export const CHENFU_BOOKS: BookId[] = BOOKS.filter((book) => book.corpus === 'chenfu').map(
  (book) => book.id,
)

export const CLAUSE_BOOKS: BookId[] = BOOKS.filter((book) => book.hasClauses).map((book) => book.id)
`
}
