import { canonicalizeHerbName, listKnownHerbs } from './herbs.ts'
import { toSimplifiedChinese } from './wiki.ts'

/** 陈傅方中常见别名 → 标准名 */
const CHENFU_ALIASES: Record<string, string> = {
  生军: '大黄',
  生軍: '大黄',
  黑丑: '牵牛子',
  白丑: '牵牛子',
  黑醜: '牵牛子',
  白醜: '牵牛子',
  黑芥穗: '荆芥穗',
  芥穗: '荆芥穗',
  荆芥: '荆芥',
  荊芥: '荆芥',
  干葛: '葛根',
  乾葛: '葛根',
  元参: '玄参',
  玄參: '玄参',
  山茱: '山茱萸',
  山萸肉: '山茱萸',
  破故纸: '补骨脂',
  破故紙: '补骨脂',
  菟丝: '菟丝子',
  菟絲: '菟丝子',
  枸杞: '枸杞子',
  牛膝: '牛膝',
  怀牛膝: '牛膝',
  川牛膝: '川牛膝',
  熟地: '熟地黄',
  熟地黄: '熟地黄',
  生地: '生地黄',
  生地黄: '生地黄',
  干地: '干地黄',
  白朮: '白术',
  苍朮: '苍术',
  白芍药: '白芍',
  赤芍药: '赤芍',
  芍药: '白芍',
  山查: '山楂',
  楂肉: '山楂',
  谷芽: '谷芽',
  麦芽: '麦芽',
  神麴: '神曲',
  神曲: '神曲',
  香附: '香附',
  香附米: '香附',
  益母: '益母草',
  益母草: '益母草',
  车前: '车前子',
  車前子: '车前子',
  芡实: '芡实',
  芡實: '芡实',
  白果: '白果',
  银花: '金银花',
  金银花: '金银花',
  连翘: '连翘',
  連翹: '连翘',
  梔子: '栀子',
  山栀: '栀子',
  山梔: '栀子',
  茵陈: '茵陈',
  茵陳: '茵陈',
  青蒿: '青蒿',
  香薷: '香薷',
  干姜: '干姜',
  炮姜: '炮姜',
  炮薑: '炮姜',
  吴萸: '吴茱萸',
  吳茱萸: '吴茱萸',
  萸肉: '山茱萸',
  枣仁: '酸枣仁',
  酸枣仁: '酸枣仁',
  远志: '远志',
  遠志: '远志',
  菖蒲: '石菖蒲',
  石菖蒲: '石菖蒲',
  天花粉: '天花粉',
  花粉: '天花粉',
  瓜蒌: '瓜蒌',
  栝蒌: '瓜蒌',
  枳壳: '枳壳',
  枳實: '枳实',
  厚朴: '厚朴',
  砂仁: '砂仁',
  木香: '木香',
  槟榔: '槟榔',
  三棱: '三棱',
  莪术: '莪术',
  莪朮: '莪术',
  巴戟: '巴戟天',
  巴戟天: '巴戟天',
  杜仲: '杜仲',
  续断: '续断',
  續斷: '续断',
  川断: '续断',
  当归: '当归',
  當歸: '当归',
  川芎: '川芎',
  丹参: '丹参',
  丹參: '丹参',
  红花: '红花',
  紅花: '红花',
  桃仁: '桃仁',
  泽泻: '泽泻',
  澤瀉: '泽泻',
  猪苓: '猪苓',
  豬苓: '猪苓',
  滑石: '滑石',
  木通: '木通',
  通草: '通草',
  灯心: '灯心草',
  燈心: '灯心草',
  黄连: '黄连',
  黃連: '黄连',
  黄芩: '黄芩',
  黃芩: '黄芩',
  黄柏: '黄檗',
  黃柏: '黄檗',
  黄檗: '黄檗',
  知母: '知母',
  石膏: '石膏',
  竹叶: '竹叶',
  竹葉: '竹叶',
  麦冬: '麦冬',
  麥冬: '麦冬',
  麦门冬: '麦冬',
  天冬: '天冬',
  五味: '五味子',
  五味子: '五味子',
  肉桂: '肉桂',
  桂心: '肉桂',
  附子: '附子',
  制附子: '附子',
  人参: '人参',
  人參: '人参',
  党参: '党参',
  黨參: '党参',
  黄芪: '黄芪',
  黃芪: '黄芪',
  黄耆: '黄芪',
  白术: '白术',
  茯苓: '茯苓',
  甘草: '甘草',
  炙甘草: '甘草',
  陈皮: '陈皮',
  陳皮: '陈皮',
  半夏: '半夏',
  柴胡: '柴胡',
  升麻: '升麻',
  独活: '独活',
  獨活: '独活',
  羌活: '羌活',
  防风: '防风',
  防風: '防风',
  白芷: '白芷',
  细辛: '细辛',
  細辛: '细辛',
  麻黄: '麻黄',
  麻黃: '麻黄',
  桂枝: '桂枝',
  生姜: '生姜',
  生薑: '生姜',
  大枣: '大枣',
  大棗: '大枣',
  杏仁: '杏仁',
  桔梗: '桔梗',
  贝母: '贝母',
  貝母: '贝母',
  川贝: '川贝母',
  浙贝: '浙贝母',
  阿胶: '阿胶',
  阿膠: '阿胶',
  鹿角胶: '鹿角胶',
  龟板: '龟甲',
  龜板: '龟甲',
  鳖甲: '鳖甲',
  鱉甲: '鳖甲',
  牡蛎: '牡蛎',
  牡蠣: '牡蛎',
  龙骨: '龙骨',
  龍骨: '龙骨',
  珍珠: '珍珠',
  朱砂: '朱砂',
  琥珀: '琥珀',
  犀角: '犀角',
  羚羊角: '羚羊角',
  牛黄: '牛黄',
  牛黃: '牛黄',
  麝香: '麝香',
  冰片: '冰片',
  薄荷: '薄荷',
  菊花: '菊花',
  桑叶: '桑叶',
  桑葉: '桑叶',
  钩藤: '钩藤',
  鉤藤: '钩藤',
  天麻: '天麻',
  全蝎: '全蝎',
  全蠍: '全蝎',
  僵蚕: '僵蚕',
  殭蠶: '僵蚕',
  地龙: '地龙',
  地龍: '地龙',
  水蛭: '水蛭',
  虻虫: '虻虫',
  土鳖: '䗪虫',
  䗪虫: '䗪虫',
  薏苡仁: '薏苡仁',
  薏仁: '薏苡仁',
  扁豆: '白扁豆',
  白扁豆: '白扁豆',
  山药: '山药',
  山藥: '山药',
  莲子: '莲子',
  蓮子: '莲子',
  莲肉: '莲子',
  芡肉: '芡实',
  金樱子: '金樱子',
  覆盆子: '覆盆子',
  桑螵蛸: '桑螵蛸',
  益智: '益智仁',
  益智仁: '益智仁',
  乌药: '乌药',
  烏藥: '乌药',
  小茴: '小茴香',
  小茴香: '小茴香',
  荔枝核: '荔枝核',
  橘核: '橘核',
  延胡: '延胡索',
  延胡索: '延胡索',
  元胡: '延胡索',
  郁金: '郁金',
  鬱金: '郁金',
  姜黄: '姜黄',
  薑黃: '姜黄',
  丹皮: '牡丹皮',
  牡丹皮: '牡丹皮',
  地骨皮: '地骨皮',
  青皮: '青皮',
  枳实: '枳实',
  莱菔子: '莱菔子',
  萊菔子: '莱菔子',
  苏子: '紫苏子',
  紫苏子: '紫苏子',
  苏叶: '紫苏叶',
  紫苏: '紫苏叶',
  藿香: '藿香',
  佩兰: '佩兰',
  佩蘭: '佩兰',
  苍耳: '苍耳子',
  苍耳子: '苍耳子',
  辛夷: '辛夷',
  白蒺藜: '蒺藜',
  蒺藜: '蒺藜',
  草决明: '决明子',
  决明子: '决明子',
  木贼: '木贼',
  木賊: '木贼',
  谷精草: '谷精草',
  密蒙花: '密蒙花',
  夜明砂: '夜明砂',
  蝉蜕: '蝉蜕',
  蟬蛻: '蝉蜕',
  蛇床子: '蛇床子',
  苦参: '苦参',
  苦參: '苦参',
  白鲜皮: '白鲜皮',
  白鮮皮: '白鲜皮',
  地肤子: '地肤子',
  地膚子: '地肤子',
  椿皮: '椿根皮',
  椿根皮: '椿根皮',
  黄精: '黄精',
  黃精: '黄精',
  玉竹: '玉竹',
  沙参: '北沙参',
  北沙参: '北沙参',
  南沙参: '南沙参',
  石斛: '石斛',
  百合: '百合',
  百部: '百部',
  款冬: '款冬花',
  款冬花: '款冬花',
  紫菀: '紫菀',
  紫苑: '紫菀',
  白前: '白前',
  前胡: '前胡',
  旋覆花: '旋覆花',
  旋复花: '旋覆花',
  葶苈子: '葶苈子',
  桑白皮: '桑白皮',
  地榆: '地榆',
  槐花: '槐花',
  侧柏叶: '侧柏叶',
  側柏葉: '侧柏叶',
  白茅根: '白茅根',
  茅根: '白茅根',
  茜草: '茜草',
  蒲黄: '蒲黄',
  蒲黃: '蒲黄',
  三七: '三七',
  血余: '血余炭',
  血余炭: '血余炭',
  棕榈炭: '棕榈炭',
  艾叶: '艾叶',
  艾葉: '艾叶',
  炮姜炭: '炮姜',
  荆芥炭: '荆芥',
  贯众: '贯众',
  貫眾: '贯众',
  鹤虱: '鹤虱',
  使君子: '使君子',
  苦楝皮: '苦楝皮',
  雷丸: '雷丸',
  槟榔片: '槟榔',
  大腹皮: '大腹皮',
  草果: '草果',
  草豆蔻: '草豆蔻',
  白豆蔻: '白豆蔻',
  豆蔻: '白豆蔻',
  肉豆蔻: '肉豆蔻',
  丁香: '丁香',
  沉香: '沉香',
  檀香: '檀香',
  降香: '降香',
  乳香: '乳香',
  没药: '没药',
  沒藥: '没药',
  血竭: '血竭',
  儿茶: '儿茶',
  兒茶: '儿茶',
  自然铜: '自然铜',
  自然銅: '自然铜',
  骨碎补: '骨碎补',
  骨碎補: '骨碎补',
  续断炭: '续断',
  狗脊: '狗脊',
  千年健: '千年健',
  伸筋草: '伸筋草',
  透骨草: '透骨草',
  威灵仙: '威灵仙',
  威靈仙: '威灵仙',
  秦艽: '秦艽',
  防己: '防己',
  木瓜: '木瓜',
  蚕沙: '蚕沙',
  蠶沙: '蚕沙',
  海桐皮: '海桐皮',
  五加皮: '五加皮',
  桑枝: '桑枝',
  桂枝尖: '桂枝',
  生姜皮: '生姜',
  茯苓皮: '茯苓',
  大腹子: '槟榔',
  橘红: '橘红',
  橘紅: '橘红',
  化橘红: '橘红',
  佛手: '佛手',
  香橼: '香橼',
  香櫞: '香橼',
  薤白: '薤白',
  瓜蒌皮: '瓜蒌',
  瓜蒌仁: '瓜蒌子',
  瓜蒌子: '瓜蒌子',
  竹茹: '竹茹',
  竹沥: '竹沥',
  竹瀝: '竹沥',
  胆星: '胆南星',
  胆南星: '胆南星',
  天南星: '天南星',
  白附子: '白附子',
  白芥子: '白芥子',
  芥子: '白芥子',
  皂角: '皂荚',
  皂荚: '皂荚',
  皂角刺: '皂角刺',
  穿山甲: '穿山甲',
  王不留: '王不留行',
  王不留行: '王不留行',
  路路通: '路路通',
  丝瓜络: '丝瓜络',
  絲瓜絡: '丝瓜络',
  冬瓜皮: '冬瓜皮',
  冬瓜子: '冬瓜子',
  赤小豆: '赤小豆',
  绿豆: '绿豆',
  綠豆: '绿豆',
  黑豆: '黑豆',
  大豆黄卷: '大豆黄卷',
  麻仁: '火麻仁',
  火麻仁: '火麻仁',
  郁李仁: '郁李仁',
  鬱李仁: '郁李仁',
  松子仁: '松子仁',
  柏子仁: '柏子仁',
  胡桃肉: '核桃仁',
  核桃仁: '核桃仁',
  芝麻: '黑芝麻',
  黑芝麻: '黑芝麻',
  蜂蜜: '蜂蜜',
  饴糖: '饴糖',
  膠飴: '饴糖',
  粳米: '粳米',
  糯米: '糯米',
  小麦: '小麦',
  小麥: '小麦',
  浮小麦: '浮小麦',
  浮小麥: '浮小麦',
  稻芽: '稻芽',
  鸡内金: '鸡内金',
  雞內金: '鸡内金',
  鸡子黄: '鸡子黄',
  雞子黃: '鸡子黄',
  猪胆汁: '猪胆汁',
  童便: '人中白',
  人中白: '人中白',
  秋石: '秋石',
  紫河车: '紫河车',
  紫河車: '紫河车',
  脐带: '脐带',
  臍帶: '脐带',
  海螵蛸: '海螵蛸',
  乌贼骨: '海螵蛸',
  瓦楞子: '瓦楞子',
  海蛤壳: '海蛤壳',
  蛤粉: '海蛤壳',
  石决明: '石决明',
  石決明: '石决明',
  珍珠母: '珍珠母',
  磁石: '磁石',
  代赭石: '代赭石',
  赭石: '代赭石',
  赤石脂: '赤石脂',
  禹余粮: '禹余粮',
  禹餘糧: '禹余粮',
  炉甘石: '炉甘石',
  爐甘石: '炉甘石',
  硼砂: '硼砂',
  芒硝: '芒硝',
  玄明粉: '玄明粉',
  朴硝: '芒硝',
  硫黄: '硫黄',
  硫黃: '硫黄',
  雄黄: '雄黄',
  雄黃: '雄黄',
  轻粉: '轻粉',
  輕粉: '轻粉',
  铅丹: '铅丹',
  鉛丹: '铅丹',
  水银: '水银',
  水銀: '水银',
  砒霜: '砒霜',
  巴豆: '巴豆',
  干漆: '干漆',
  乾漆: '干漆',
  斑蝥: '斑蝥',
  斑蝥: '斑蝥',
  蜈蚣: '蜈蚣',
  蟾酥: '蟾酥',
  蜂房: '蜂房',
  露蜂房: '蜂房',
  白花蛇: '白花蛇',
  乌梢蛇: '乌梢蛇',
  烏梢蛇: '乌梢蛇',
  蕲蛇: '蕲蛇',
  蘄蛇: '蕲蛇',
  地鳖虫: '䗪虫',
  土鳖虫: '䗪虫',
}

/** 原文缺字修复：上下文关键词 → 完整药名 */
const MISSING_CHAR_FIXES: Array<{ broken: RegExp; fixed: string }> = [
  { broken: /黄\s*(?=同功|一两|二两|三两|五钱|一两|黄芪)/, fixed: '黄芪' },
  { broken: /黃\s*(?=同功|一兩|二兩)/, fixed: '黄芪' },
  { broken: /白\s*(?=一两土炒|一两，土炒)/, fixed: '白术' },
]

let lexiconCache: string[] | null = null
let lexiconSetCache: Set<string> | null = null

export function applyMissingCharFixes(text: string): string {
  let result = text
  for (const fix of MISSING_CHAR_FIXES) {
    result = result.replace(fix.broken, fix.fixed)
  }
  return result
}

export function canonicalizeChenfuHerb(rawName: string): string {
  const simplified = toSimplifiedChinese(rawName)
    .replace(/[（(].*?[）)]/g, '')
    .replace(/\s+/g, '')
    .trim()
  if (!simplified) return ''
  if (CHENFU_ALIASES[simplified]) return CHENFU_ALIASES[simplified]
  const fromJingfang = canonicalizeHerbName(simplified)
  if (fromJingfang) return fromJingfang
  return simplified
}

/** 从本草新编 raw 文本提取篇名药名 */
export function extractBencaoHerbNames(bencaoRaw: string): string[] {
  const names: string[] = []
  const re = /<篇名>([^\n<]+)/g
  let match: RegExpExecArray | null
  while ((match = re.exec(bencaoRaw)) !== null) {
    const name = canonicalizeChenfuHerb(match[1]!.trim())
    if (name && name.length >= 1 && name.length <= 6) names.push(name)
  }
  return [...new Set(names)]
}

export function buildHerbLexicon(extraNames: string[] = []): string[] {
  if (lexiconCache && extraNames.length === 0) return lexiconCache
  const names = new Set<string>()
  for (const name of listKnownHerbs()) names.add(name)
  for (const name of Object.values(CHENFU_ALIASES)) names.add(name)
  for (const name of Object.keys(CHENFU_ALIASES)) {
    const canon = canonicalizeChenfuHerb(name)
    if (canon) names.add(canon)
  }
  for (const name of extraNames) {
    const canon = canonicalizeChenfuHerb(name)
    if (canon) names.add(canon)
  }
  // 按长度降序，便于正向最大匹配
  const sorted = [...names].filter((n) => n.length >= 1).sort((a, b) => b.length - a.length || a.localeCompare(b, 'zh-CN'))
  if (extraNames.length === 0) {
    lexiconCache = sorted
    lexiconSetCache = new Set(sorted)
  }
  return sorted
}

export function getLexiconSet(extraNames: string[] = []): Set<string> {
  if (lexiconSetCache && extraNames.length === 0) return lexiconSetCache
  return new Set(buildHerbLexicon(extraNames))
}

/**
 * 正向最大匹配：把「甘草人参柴胡栀子」切成药名数组。
 */
export function segmentHerbNames(glued: string, lexicon?: string[]): string[] {
  const text = toSimplifiedChinese(glued).replace(/\s+/g, '')
  if (!text) return []
  const dict = lexicon ?? buildHerbLexicon()
  const result: string[] = []
  let i = 0
  while (i < text.length) {
    let matched = false
    for (const name of dict) {
      if (text.startsWith(name, i)) {
        result.push(canonicalizeChenfuHerb(name) || name)
        i += name.length
        matched = true
        break
      }
    }
    if (!matched) {
      // 跳过单字噪声，或收纳未知二字
      if (i + 2 <= text.length) {
        const two = text.slice(i, i + 2)
        if (!/[一二三四五六七八九十百半两钱分厘各]/.test(two)) {
          result.push(canonicalizeChenfuHerb(two) || two)
          i += 2
          continue
        }
      }
      i += 1
    }
  }
  return result.filter(Boolean)
}

export function resetLexiconCache(): void {
  lexiconCache = null
  lexiconSetCache = null
}
